package com.technfest.technfestcrm.model

data class LeadResponseItem(
    val campaignCategoryId: Int,
    val campaignCategoryName: String,
    val campaignId: Int,
    val campaignName: String,
    val company: Any,
    val completedAt: Any,
    val createdAt: String,
    val email: String,
    val followupStatus: Any,
    val fullName: String,
    val id: Int,
    val leadRequirement: Any,
    val location: Any,
    val mobile: String,
    val nextFollowupAt: Any,
    val notes: String,
    val ownerName: Any,
    val ownerUserId: Any,
    val priority: String,
    val rescheduledAt: Any,
    val source: Any,
    val sourceDetails: String,
    val stage: Any,
    val status: String,
    val teamName: Any,
    val updatedAt: String,
    val whatsappSentAt: Any,
    val workspaceCode: String,
    val workspaceId: Int,
    val workspaceName: String
)