package com.technfest.technfestcrm.model

//data class LeadResponseItem(
//    val campaignCategoryId: Int,
//    val campaignCategoryName: String,
//    val campaignId: Int,
//    val campaignName: String,
//    val company: Any,
//    val completedAt: Any,
//    val createdAt: String,
//    val email: String,
//    val followupStatus: Any,
//    var fullName: String,
//    val id: Int,
//    val leadRequirement: Any,
//    val location: Any,
//    val mobile: String,
//    val nextFollowupAt: String?,
//    val notes: String,
//    val ownerName: Any,
//    val ownerUserId: Int,
//    val priority: String,
//    val rescheduledAt: Any,
//    val source: Any,
//    val sourceDetails: String,
//    val stage: Any,
//    val status: String,
//    val teamName: Any,
//    val updatedAt: String,
//    val whatsappSentAt: Any,
//    val workspaceCode: String,
//    val workspaceId: Int,
//    val workspaceName: String
//)

data class LeadResponseItem(
    val campaignCategoryId: Int = 0,
    val campaignCategoryName: String = "",
    val campaignId: Int = 0,
    val campaignName: String = "",
    val company: Any? = null,
    val completedAt: Any? = null,
    val createdAt: String = "",
    val email: String = "",
    val followupStatus: Any? = null,
    var fullName: String = "",
    val id: Int = 0,
    val leadRequirement: Any? = null,
    val location: Any? = null,
    val mobile: String = "",
    val nextFollowupAt: String? = null,
    val notes: String = "",
    val ownerName: Any? = null,
    val ownerUserId: Int = 0,
    val priority: String = "",
    val rescheduledAt: Any? = null,
    val source: Any? = null,
    val sourceDetails: String = "",
    val stage: Any? = null,
    val status: String = "",
    val teamName: Any? = null,
    val updatedAt: String = "",
    val whatsappSentAt: Any? = null,
    val workspaceCode: String = "",
    val workspaceId: Int = 0,
    val workspaceName: String = ""
)
